'use client';
import {useEffect,useRef,useState} from 'react';
import {AudioLines,ArrowUpRight,BookOpen,BriefcaseBusiness,ChartNoAxesCombined,CircleHelp,Code2,Play,Sparkles,Mic,Square,Volume2,Download,Plus,Check,ChevronRight,Search,Trash2,Settings2,Clock3,Pause,RotateCcw,FileText,ExternalLink} from 'lucide-react';
import {Profile,Story,Session,Review,emptyProfile,questions,categories,evaluate,guidance,capabilities} from '../lib/interview';
const navigation=[['Practice room',Play],['Story library',BookOpen],['Role & resume',BriefcaseBusiness],['Question bank',CircleHelp],['Technical lab',Code2],['Progress',ChartNoAxesCombined],['Research & settings',Settings2]] as const;
const blankStory=():Story=>({id:crypto.randomUUID(),title:'',tag:'Leadership',situation:'',task:'',action:'',result:''});
function download(name:string,text:string,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function time(n:number){return Math.floor(n/60).toString().padStart(2,'0')+':'+(n%60).toString().padStart(2,'0')}
async function api(path:string,options?:RequestInit):Promise<any>{const r=await fetch(path,options);const data:any=await r.json();if(!r.ok)throw new Error(data.error||'Something went wrong. Please retry.');return data}
export default function Workspace(){
 const [tab,setTab]=useState('Practice room'),[profile,setProfile]=useState<Profile>(emptyProfile),[stories,setStories]=useState<Story[]>([]),[sessions,setSessions]=useState<Session[]>([]);
 const [loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(true),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [category,setCategory]=useState('Behavioral'),[question,setQuestion]=useState(questions[0].text),[answer,setAnswer]=useState(''),[custom,setCustom]=useState(''),[review,setReview]=useState<Review|null>(null),[aiText,setAiText]=useState(''),[aiAvailable,setAiAvailable]=useState(false),[aiBusy,setAiBusy]=useState(false),[aiEnabled,setAiEnabled]=useState(false);
 const [running,setRunning]=useState(false),[seconds,setSeconds]=useState(0),[listening,setListening]=useState(false),[interim,setInterim]=useState(''),[language,setLanguage]=useState('en-US'),[voiceSeconds,setVoiceSeconds]=useState(0),[voiceOnly,setVoiceOnly]=useState(false);
 const recognition=useRef<any>(null),voiceStart=useRef(0),activeVoice=useRef(false),aiAbort=useRef<AbortController|null>(null),sessionId=useRef(''),[savedId,setSavedId]=useState(''),[storyDraft,setStoryDraft]=useState<Story|null>(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[selectedSession,setSelectedSession]=useState<Session|null>(null),[mock,setMock]=useState(false),[round,setRound]=useState(1);
 async function load(){setLoading(true);try{const d=await api('/api/workspace');setSignedIn(true);setProfile(d.records.find((r:any)=>r.kind==='profile')?.data||emptyProfile);setStories(d.records.filter((r:any)=>r.kind==='story').map((r:any)=>r.data));setSessions(d.records.filter((r:any)=>r.kind==='session').map((r:any)=>r.data))}catch(e){setNotice((e as Error).message);if((e as Error).message.includes('Sign in'))setSignedIn(false)}finally{setLoading(false)}}
 useEffect(()=>{load();api('/api/coach').then(d=>setAiAvailable(d.available)).catch(()=>{});return()=>{recognition.current?.abort();aiAbort.current?.abort();window.speechSynthesis?.cancel()}},[]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[running]);
 useEffect(()=>{if(tab!=='Practice room'&&tab!=='Technical lab'){recognition.current?.stop();setRunning(false);window.speechSynthesis?.cancel()}},[tab]);
 const notes=guidance(category,profile,stories,question),metrics=evaluate(answer,voiceOnly?voiceSeconds:0,category);
 const roleQuestions=profile.role?[{category:'Role-specific',text:'What makes you a strong fit for '+profile.role+(profile.company?' at '+profile.company:'')+'?'},{category:'Role-specific',text:'How would you measure success in your first 90 days as '+profile.role+'?'}]:[];
 const bank=[...roleQuestions,...questions];
 const filtered=bank.filter(q=>(filter==='All'||q.category===filter)&&(q.text+' '+q.category).toLowerCase().includes(search.toLowerCase()));
 const completed=sessions.length,average=completed?Math.round(sessions.reduce((n,s)=>n+s.review.score,0)/completed):0;
 function stopVoice(){recognition.current?.stop();setRunning(false)}
 function resetQuestion(q:string,c:string){if(answer.trim()&&!savedId&&!window.confirm('Replace this unsaved answer?'))return false;activeVoice.current=false;recognition.current?.abort();recognition.current=null;setListening(false);aiAbort.current?.abort();window.speechSynthesis?.cancel();setQuestion(q);setCategory(c);setAnswer('');setReview(null);setAiText('');setSeconds(0);setVoiceSeconds(0);setVoiceOnly(false);setRunning(false);setInterim('');setSavedId('');sessionId.current='';setNotice('');return true}
 function changeTab(t:string){if(t==='Technical lab'&&!['Technical','System design'].includes(category)){if(!resetQuestion(questions.find(q=>q.category==='Technical')!.text,'Technical'))return}if(t==='Practice room'&&['Technical','System design'].includes(category)){if(!resetQuestion(questions[0].text,'Behavioral'))return}setTab(t)}
 function next(){if(mock&&round>=5){if(answer.trim()&&!savedId&&!window.confirm('Finish without saving this answer?'))return;stopVoice();setMock(false);setTab('Progress');setNotice('Mock interview complete. Review your saved answers below.');return}const items=bank.filter(q=>q.category===category);const index=items.findIndex(q=>q.text===question);if(resetQuestion(items[(index+1)%items.length].text,category)&&mock)setRound(r=>r+1)}
 async function save(kind:string,data:any){setBusy(true);setNotice('');try{return await api('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data})})}catch(e){setNotice((e as Error).message);return null}finally{setBusy(false)}}
 async function saveAnswer(){stopVoice();if(!answer.trim())return;const r=evaluate(answer,voiceOnly?voiceSeconds:0,category);setReview(r);sessionId.current ||= crypto.randomUUID();const s={id:sessionId.current,question,answer,category,seconds:voiceOnly?voiceSeconds:0,createdAt:new Date().toISOString(),ai:aiText||undefined};const result=await save('session',s);if(result){setSessions(prev=>[result.data,...prev.filter(x=>x.id!==s.id)]);setSavedId(s.id);setNotice('Answer and review saved to your progress.')}}
 async function saveStory(){if(!storyDraft?.title.trim()){setNotice('Give this story a title.');return}const result=await save('story',storyDraft);if(result){setStories(s=>[storyDraft,...s.filter(x=>x.id!==storyDraft.id)]);setStoryDraft(null);setNotice('Story saved.')}}
 async function remove(id:string,kind:string){if(!window.confirm('Delete this '+kind+' permanently?'))return;try{await api('/api/workspace?id='+encodeURIComponent(id),{method:'DELETE'});if(kind==='story')setStories(s=>s.filter(x=>x.id!==id));else{setSessions(s=>s.filter(x=>x.id!==id));setSelectedSession(null)}setNotice('Deleted.')}catch(e){setNotice((e as Error).message)}}
 async function askAI(){setAiBusy(true);setNotice('');const controller=new AbortController();aiAbort.current=controller;try{const d=await api('/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,answer,category,profile,stories:stories.slice(0,5)}),signal:controller.signal});setAiText(d.text)}catch(e){if((e as Error).name!=='AbortError')setNotice((e as Error).message)}finally{setAiBusy(false)}}
 function listen(){if(listening){recognition.current?.stop();return}const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setNotice('Voice transcription is unavailable in this browser. Try Chrome or Edge, or type your answer.');return}const rec=new SR();recognition.current=rec;rec.lang=language;rec.continuous=true;rec.interimResults=true;
 rec.onstart=()=>{voiceStart.current=Date.now();activeVoice.current=true;setListening(true);setRunning(true);if(!answer.trim())setVoiceOnly(true)};
 rec.onresult=(e:any)=>{let final='',partial='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)final+=e.results[i][0].transcript+' ';else partial+=e.results[i][0].transcript}if(final)setAnswer(a=>(a+' '+final).trim());setInterim(partial);setReview(null);setSavedId('')};
 rec.onerror=(e:any)=>{setNotice(e.error==='not-allowed'?'Microphone permission was denied. Enable it in your browser or type your answer.':'Transcription stopped ('+e.error+'). You can retry or continue typing.')};
 rec.onend=()=>{if(activeVoice.current){setVoiceSeconds(s=>s+(Date.now()-voiceStart.current)/1000);activeVoice.current=false}setListening(false);setInterim('');setRunning(false)};
 try{rec.start()}catch{setNotice('Could not start the microphone. Try again or type your answer.')}
 }
 function speak(){if(!window.speechSynthesis){setNotice('Read-aloud is unavailable in this browser.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(question);u.lang=language;window.speechSynthesis.speak(u)}
 function answerEdit(value:string){aiAbort.current?.abort();setAnswer(value);setVoiceOnly(false);setReview(null);setSavedId('');setAiText('')}
 function sessionExport(s:Session){download('interview-review-'+s.id.slice(0,8)+'.md','# Interview review\n\n'+s.question+'\n\n'+s.answer+'\n\n## Built-in rubric\n\n'+s.review.score+'% checks met. This is a keyword-based coaching aid, not a hiring prediction.\n\n'+s.review.checks.map(c=>(c.pass?'✓ ':'○ ')+c.label+': '+c.advice).join('\n')+'\n\nNext step: '+s.review.next+(s.ai?'\n\n## AI feedback\n'+s.ai:''))}
 const isRoom=tab==='Practice room'||tab==='Technical lab';
 return <div className="shell"><aside><div className="brand"><AudioLines/> Interview<span>OS</span></div><div className="workspace-label">YOUR WORKSPACE</div><nav>{navigation.map(([label,Icon])=><button key={label} onClick={()=>changeTab(label)} className={label===tab?'selected':''}><Icon size={18}/>{label}</button>)}</nav><div className="aside-bottom"><div className="private-label"><span className="avatar">YO</span><div>Your workspace<small>Private · saved to your account</small></div></div><p>One good answer at a time.</p></div></aside><main><header><span>Workspace / <b>{tab}</b></span><span className="pill">{aiAvailable&&aiEnabled?'AI + built-in coach':'Built-in coach'}</span></header><section className="page">
 {loading&&<div className="banner" role="status">Loading your saved workspace…</div>}
 {notice&&<div className="banner" role="status"><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Dismiss notification">×</button></div>}
 {!signedIn&&<div className="banner"><span>You can try practice now. Sign in to save your stories and progress.</span><a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in</a><button onClick={load}>Retry</button></div>}
 {isRoom&&<><div className="heading"><div><div className="eyebrow">{tab==='Technical lab'?'THINK IT THROUGH. TALK IT THROUGH.':'A LITTLE PRACTICE. A BIG DIFFERENCE.'}</div><h1>{tab==='Technical lab'?'Show your thinking.':'Your next great answer.'}</h1><p>{profile.role?profile.role+(profile.company?' · '+profile.company:''):'Make your experience the strongest thing in the room.'}</p></div><button onClick={()=>{setMock(!mock);setRound(1);setNotice(mock?'Mock interview ended. Saved answers are in Progress.':'Mock interview started. Answer, review, then advance through five questions.')}}><Play size={16}/>{mock?'End mock interview':'Start mock interview'}</button></div>
 <div className="toolbar"><div className="tabs">{(tab==='Technical lab'?['Technical','System design']:['Behavioral','Leadership','Role-specific','Recruiter','Negotiation']).map(c=><button key={c} className={category===c?'active':''} onClick={()=>resetQuestion(bank.find(q=>q.category===c)!.text,c)}>{c}</button>)}</div><span className="timer"><Clock3 size={16}/>{time(seconds)}<button aria-label={running?'Pause timer':'Start timer'} onClick={()=>{if(listening)stopVoice();else setRunning(!running)}}>{running?<Pause size={14}/>:<Play size={14}/>}</button></span></div>
 {mock&&<div className="mock-progress"><span>Mock interview · Question {Math.min(round,5)} of 5</span><progress max={5} value={Math.min(round-1,5)}/>{round>5&&<span>Practice complete. Review your saved answers in Progress.</span>}</div>}
 <div className="room"><div className="practice"><div className="panel-top"><span className="tag">{category.toUpperCase()}</span><button className="icon-button" aria-label="Read question aloud" onClick={speak}><Volume2 size={18}/></button></div><h2>{question}</h2><p className="muted">{category==='Technical'||category==='System design'?'Explain your approach, trade-offs, and how you would test it.':'Take a breath. Set the scene, then focus on what you did.'}</p>
 <label htmlFor="answer">{tab==='Technical lab'?'Your solution & explanation':'Your answer'}</label><textarea id="answer" className={tab==='Technical lab'?'code-input':''} maxLength={30000} value={answer} onChange={e=>answerEdit(e.target.value)} placeholder={tab==='Technical lab'?'Write your approach or paste code here. Code is reviewed, not executed.':'Start with the situation. What was at stake?'} /><div className="interim" aria-live="polite">{interim|| (listening?'Listening…':'')}</div>
 <div className="voice-row"><button onClick={listen} className={listening?'recording':''}>{listening?<Square size={16}/>:<Mic size={16}/>} {listening?'Stop microphone':'Speak your answer'}</button><select aria-label="Speech language" value={language} disabled={listening} onChange={e=>setLanguage(e.target.value)}><option value="en-US">English</option><option value="es-ES">Español</option><option value="fr-FR">Français</option><option value="de-DE">Deutsch</option><option value="hi-IN">हिन्दी</option><option value="ja-JP">日本語</option></select></div>
 <p className="micro-copy">Microphone starts only when you choose. Your browser may send audio to its speech service. Transcripts are saved only with your review.</p>
 <div className="panel-bottom"><span>{metrics.words} words · {metrics.fillers} filler words</span><button disabled={!answer.trim()||busy||listening||loading} className="primary" onClick={saveAnswer}>{busy?'Saving…':savedId?'Update review':'Review & save'} <Sparkles size={16}/></button></div>
 {review&&<ReviewPanel review={review}/>}
 <div className="room-footer"><button onClick={next}>Next question <ChevronRight size={16}/></button>{answer&&<button onClick={()=>download('answer-draft.txt',question+'\n\n'+answer)}><Download size={15}/>Export draft</button>}</div>
 <details className="custom"><summary>Use your own interview question</summary><label htmlFor="custom">Question</label><input id="custom" maxLength={3000} value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Paste a question to practice"/><button disabled={!custom.trim()} onClick={()=>resetQuestion(custom.trim(),category)}>Use question</button></details></div>
 <div className="coach"><div className="coach-title"><Sparkles size={20}/><h3>Your coaching notes</h3></div><p>Give your answer a clear shape.</p>{notes.steps.map((x,i)=><div className="step" key={x}><span>{notes.labels[i]}</span><p>{x}</p></div>)}
 <div className="context-note"><BriefcaseBusiness size={17}/><p>{notes.context}</p></div>
 {notes.story?<div className="story-match"><small>FROM YOUR STORY LIBRARY</small><h3>{notes.story.title}</h3><p>{notes.story.action}</p><button onClick={()=>{setTab('Story library');setStoryDraft(notes.story!)}}>Review story <ChevronRight size={14}/></button></div>:<div className="tip">Build a few real stories you can adapt to different questions.<button className="text-button" onClick={()=>setTab('Story library')}>Open story library <ArrowUpRight size={15}/></button></div>}
 {aiAvailable&&aiEnabled?<><button className="primary full" disabled={aiBusy} onClick={askAI}><Sparkles size={16}/>{aiBusy?'Thinking…':'Get AI coaching'}</button><p className="micro-copy">Sends this answer, your role, resume, and up to five stories to OpenAI.</p></>:<p className="micro-copy">Built-in coach · framework guidance and transparent keyword checks. Optional AI can add personalized feedback.</p>}
 {aiText&&<div className="ai-feedback"><h3>AI coaching</h3><p>{aiText}</p></div>}</div></div>
 <div className="bottom-strip"><div><span className="metric-value">{completed}</span><span>answers practiced</span></div><div><span className="metric-value">{stories.length}</span><span>stories ready to use</span></div><button className="text-button" onClick={()=>setTab('Progress')}>See your progress <ArrowUpRight size={16}/></button></div></>}
 {tab==='Role & resume'&&<><PageHeading eyebrow="MAKE IT PERSONAL" title="Your experience. Your next role." text="Give your preparation a clear target."/><div className="two-col"><div className="card"><h3>Target opportunity</h3><label htmlFor="role">Role</label><input id="role" maxLength={150} value={profile.role} onChange={e=>setProfile({...profile,role:e.target.value})} placeholder="e.g. Senior Product Manager"/><label htmlFor="company">Company</label><input id="company" maxLength={150} value={profile.company} onChange={e=>setProfile({...profile,company:e.target.value})} placeholder="Company name"/><label htmlFor="job">Job description</label><textarea id="job" maxLength={30000} value={profile.job} onChange={e=>setProfile({...profile,job:e.target.value})} placeholder="Paste the responsibilities and requirements…"/><p className="micro-copy">Used as context for optional AI coaching. Company facts are not automatically researched.</p></div><div className="card"><h3>Your background</h3><label htmlFor="resume">Resume or experience notes</label><textarea id="resume" className="tall" maxLength={30000} value={profile.resume} onChange={e=>setProfile({...profile,resume:e.target.value})} placeholder="Paste your resume text, projects, skills, and achievements…"/><label className="file-label">Import plain text (.txt)<input type="file" accept=".txt,text/plain" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>100000){setNotice('Use a text file smaller than 100 KB.');return}const text=await f.text();if(text.length>30000){setNotice('Please limit your resume to 30,000 characters.');return}setProfile(p=>({...p,resume:text}))}}/></label><p className="micro-copy">Saved privately to your account. Paste text from PDF or Word files.</p></div></div><div className="actions"><button className="primary" disabled={busy||loading} onClick={async()=>{if(await save('profile',profile))setNotice('Role and resume saved.')}}>Save profile <Check size={16}/></button><button onClick={()=>{setTab('Question bank');setFilter('Role-specific')}}>Practice for this role <ArrowUpRight size={16}/></button></div></>}
 {tab==='Story library'&&<><PageHeading eyebrow="YOUR EXPERIENCE, READY TO TELL" title="Build your story bank." text="Keep the real examples that make your answers memorable." action={<button className="primary" onClick={()=>setStoryDraft(blankStory())}><Plus size={17}/>New story</button>}/>{storyDraft&&<div className="card story-editor"><h3>{stories.some(s=>s.id===storyDraft.id)?'Edit story':'A new STAR story'}</h3><div className="two-col"><div><label htmlFor="story-title">Story title</label><input id="story-title" maxLength={200} value={storyDraft.title} onChange={e=>setStoryDraft({...storyDraft,title:e.target.value})} placeholder="e.g. Turned a delayed launch around"/></div><div><label htmlFor="story-tag">Theme</label><select id="story-tag" value={storyDraft.tag} onChange={e=>setStoryDraft({...storyDraft,tag:e.target.value})}>{['Leadership','Conflict','Impact','Failure','Growth','Collaboration','Technical'].map(t=><option key={t}>{t}</option>)}</select></div></div><div className="two-col">{(['situation','task','action','result'] as const).map((field,i)=><div key={field}><label htmlFor={field}>{'STAR'[i]} · {field[0].toUpperCase()+field.slice(1)}</label><textarea id={field} maxLength={6000} value={storyDraft[field]} onChange={e=>setStoryDraft({...storyDraft,[field]:e.target.value})} placeholder={['What was happening? Why did it matter?','What were you responsible for?','What did you do and why?','What changed? Include real results and lessons.'][i]}/></div>)}</div><div className="actions"><button className="primary" disabled={busy||!storyDraft.title.trim()} onClick={saveStory}>Save story <Check size={16}/></button><button onClick={()=>{if(window.confirm('Close this story editor? Unsaved changes will be lost.'))setStoryDraft(null)}}>Cancel</button></div></div>}
 {stories.length===0&&!storyDraft?<Empty icon={<BookOpen/>} title="Your best examples belong here." text="Start with a project you are proud of, a challenge you overcame, or a lesson that changed how you work."/>:<div className="story-grid">{stories.map(s=><article className="card" key={s.id}><span className="tag">{s.tag}</span><h3>{s.title}</h3><p>{s.situation||'Add the situation to complete this story.'}</p><div className="story-result"><strong>RESULT</strong><p>{s.result||'Add your outcome.'}</p></div><div className="actions"><button onClick={()=>setStoryDraft(s)}>Edit story</button><button className="icon-button" aria-label={'Delete '+s.title} onClick={()=>remove(s.id,'story')}><Trash2 size={16}/></button></div></article>)}</div>}</>}
 {tab==='Question bank'&&<><PageHeading eyebrow="PREPARE FOR THE MOMENTS THAT MATTER" title="Find your next question." text="Explore the library or bring a question of your own."/><div className="search-row"><div className="search-field"><Search size={18}/><input aria-label="Search questions" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search questions or topics"/></div><select aria-label="Filter by interview type" value={filter} onChange={e=>setFilter(e.target.value)}>{['All',...categories].map(c=><option key={c}>{c}</option>)}</select></div><p className="muted">{filtered.length} questions</p><div className="question-list">{filtered.map((q,i)=><button key={q.text} onClick={()=>{if(resetQuestion(q.text,q.category))setTab(q.category==='Technical'||q.category==='System design'?'Technical lab':'Practice room')}}><span className="question-number">{String(i+1).padStart(2,'0')}</span><span><small>{q.category}</small><strong>{q.text}</strong></span><ArrowUpRight size={19}/></button>)}</div>{!filtered.length&&<Empty icon={<Search/>} title="No matching questions." text="Try another search or choose a different category."/>}</>}
 {tab==='Progress'&&<><PageHeading eyebrow="SMALL IMPROVEMENTS ADD UP" title="See how far you’ve come." text="Your actual practice history, with a clear next step." action={<button disabled={!sessions.length} onClick={()=>download('interviewos-export.json',JSON.stringify({profile,stories,sessions},null,2),'application/json')}><Download size={16}/>Export workspace</button>}/><div className="stats"><div className="card"><small>Answers practiced</small><strong>{completed}</strong></div><div className="card"><small>Average rubric coverage</small><strong>{completed?average+'%':'—'}</strong></div><div className="card"><small>Stories in your library</small><strong>{stories.length}</strong></div></div>{sessions.length?<><div className="card trend"><div className="section-heading"><h3>Last {Math.min(10,sessions.length)} answers</h3><small>Built-in rubric coverage</small></div><div className="bars">{sessions.slice(0,10).reverse().map((s,i)=><button aria-label={'Review answer '+(i+1)+', '+s.review.score+' percent'} key={s.id} onClick={()=>setSelectedSession(s)}><span>{s.review.score}%</span><div style={{height:Math.max(3,s.review.score)+'%'}}/><small>{i+1}</small></button>)}</div><p className="micro-copy">Keyword checks indicate structure and detail; they do not measure correctness, predict hiring, or replace human feedback. English checks may undercount other languages.</p></div><div className="two-col history"><div><h3>Session history</h3>{sessions.map(s=><button className="history-row" key={s.id} onClick={()=>setSelectedSession(s)}><span className="score-mini">{s.review.score}%</span><span><strong>{s.question}</strong><small>{s.category} · {new Date(s.createdAt).toLocaleDateString()}</small></span><ChevronRight size={16}/></button>)}</div><div className="card">{selectedSession?<><div className="section-heading"><span className="tag">{selectedSession.category}</span><button className="icon-button" aria-label="Delete session" onClick={()=>remove(selectedSession.id,'session')}><Trash2 size={16}/></button></div><h3>{selectedSession.question}</h3><p className="saved-answer">{selectedSession.answer}</p><ReviewPanel review={selectedSession.review}/>{selectedSession.ai&&<div className="ai-feedback"><h3>AI feedback</h3><p>{selectedSession.ai}</p></div>}<button onClick={()=>sessionExport(selectedSession)}><Download size={16}/>Export review</button></>:<><Sparkles className="blue"/><h3>Your next step</h3><p>{sessions[0].review.next}</p><button onClick={()=>{if(resetQuestion(sessions[0].question,sessions[0].category))setTab(['Technical','System design'].includes(sessions[0].category)?'Technical lab':'Practice room')}}>Practice again <RotateCcw size={16}/></button><p className="micro-copy">Select an answer to see its full transcript and review.</p></>}</div></div></>:<Empty icon={<ChartNoAxesCombined/>} title="Your progress starts with one answer." text="Practice a question and choose Review & save. Your feedback and history will appear here."/>}</>}
 {tab==='Research & settings'&&<><PageHeading eyebrow="RESEARCH INTO PRACTICE" title="Ten capabilities. One workspace." text="A practical synthesis of existing interview assistants, researched September 20, 2026."/><div className="card settings"><h3>Coaching engine</h3><p>{aiAvailable?'An AI provider is connected. Enable it to request personalized coaching.':'Built-in coaching is active. No AI API key is configured for this app.'}</p><label className="checkbox"><input type="checkbox" disabled={!aiAvailable} checked={aiEnabled} onChange={e=>setAiEnabled(e.target.checked)}/>Enable optional AI coaching</label><p className="micro-copy">When you request AI coaching, your selected context is sent to OpenAI. The key stays on the server. Built-in guidance works without an account with an AI provider.</p><details><summary>AI setup and current scope</summary><p>To enable AI, the site owner must connect an OpenAI API key as the OPENAI_API_KEY site secret and publish the app again. OPENAI_MODEL can select a compatible Responses API model. This build has no provider credentials and its AI responses have not been live-tested.</p><p>Voice uses browser speech recognition, not direct meeting audio capture. Technical answers are reviewed, not executed. This web app does not include a desktop overlay, screen solving, meeting integrations, or video recording.</p></details></div><div className="capabilities">{capabilities.map((c,i)=><div className="capability" key={c.title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{c.title}</h3><p>{c.detail}</p><a href={c.url} target="_blank" rel="noreferrer">Source: {c.source} <ExternalLink size={13}/></a></div></div>)}</div><div className="card"><h3>About your data</h3><p>Your role, stories, and saved reviews are stored in your private workspace. Microphone audio is not stored by this app. You can export your workspace from Progress and delete individual stories or reviews.</p><p className="micro-copy">These capabilities are selected for preparation value and recurrence across products, not a measured market-share ranking. Vendor claims are not independent performance benchmarks.</p></div></>}
 </section></main></div>
}
function PageHeading({eyebrow,title,text,action}:{eyebrow:string;title:string;text:string;action?:React.ReactNode}){return <div className="heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty card">{icon}<h3>{title}</h3><p>{text}</p></div>}
function ReviewPanel({review}:{review:Review}){return <div className="review"><div className="section-heading"><h3>Answer review</h3><strong>{review.score}% checks met</strong></div><div className="review-metrics"><span>{review.words} words</span><span>{review.fillers} fillers</span>{review.pace!==null&&<span>{review.pace} words/min</span>}</div>{review.checks.map(c=><div className={'check '+(c.pass?'pass':'')} key={c.label}><span>{c.pass?<Check size={15}/>:<CircleHelp size={15}/>}</span><div><strong>{c.label}</strong>{!c.pass&&<p>{c.advice}</p>}</div></div>)}<p className="micro-copy">Rule-based English keyword checks, not an assessment of accuracy or hiring potential. Speaking pace is shown only for unedited voice answers with at least 10 seconds of audio.</p></div>}
