import {getChatGPTUser} from '../../chatgpt-auth';
import {database} from '../../../lib/storage';
import {z} from 'zod';
import {evaluate} from '../../../lib/interview';
export const dynamic='force-dynamic';
const profile=z.object({role:z.string().max(150),company:z.string().max(150),resume:z.string().max(30000),job:z.string().max(30000)});
const story=z.object({id:z.string().uuid(),title:z.string().min(1).max(200),tag:z.string().max(80),situation:z.string().max(6000),task:z.string().max(6000),action:z.string().max(6000),result:z.string().max(6000)});
const session=z.object({id:z.string().uuid(),question:z.string().min(1).max(3000),answer:z.string().min(1).max(30000),category:z.string().max(80),seconds:z.number().min(0).max(86400),createdAt:z.string().datetime(),ai:z.string().max(20000).optional()});
const bodySchema=z.discriminatedUnion('kind',[z.object({kind:z.literal('profile'),data:profile}),z.object({kind:z.literal('story'),data:story}),z.object({kind:z.literal('session'),data:session})]);
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to save and load your workspace.'},{status:401});try{const result=await database().prepare('SELECT kind, data FROM records WHERE user_id = ? ORDER BY created_at DESC').bind(user.userId).all<{kind:string;data:string}>();return Response.json({records:result.results.map(r=>({kind:r.kind,data:JSON.parse(r.data)}))},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'Your workspace could not be loaded. Please retry.'},{status:503})}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to save your workspace.'},{status:401});if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});try{const raw=await request.text();if(raw.length>100000)return Response.json({error:'Content is too large.'},{status:413});const parsed=bodySchema.safeParse(JSON.parse(raw));if(!parsed.success)return Response.json({error:'Check your fields and try again.'},{status:400});const {kind}=parsed.data;let data:any=parsed.data.data;if(kind==='session')data={...data,review:evaluate(data.answer,data.seconds,data.category)};const id=kind==='profile'?'profile':data.id;await database().prepare('INSERT INTO records (user_id,id,kind,data,created_at) VALUES (?,?,?,?,?) ON CONFLICT(user_id,id) DO UPDATE SET data=excluded.data').bind(user.userId,id,kind,JSON.stringify(data),new Date().toISOString()).run();return Response.json({data})}catch{return Response.json({error:'Could not save. Your input is still here; please retry.'},{status:503})}}
export async function DELETE(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401});if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});const id=new URL(request.url).searchParams.get('id');if(!id||id.length>100)return Response.json({error:'Invalid record.'},{status:400});try{await database().prepare('DELETE FROM records WHERE user_id=? AND id=?').bind(user.userId,id).run();return Response.json({ok:true})}catch{return Response.json({error:'Could not delete. Please retry.'},{status:503})}}
